#cloud-config
users:
  - name: root
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
package_upgrade: true
packages:
      - ca-certificates
      - curl
      - gnupg
      - vim
      - git
      - zip
      - unzip
      - openssl
      - libssl-dev
      - build-essential
      - libclang-dev
write_files:
  - path: /etc/prometheus.yml
    content: |
      global:
        scrape_interval: 1s
  
      scrape_configs:
      - job_name: "telemetry_metrics_prometheus"
        metrics_path: "/metrics"
        static_configs:
        - targets: ["host.docker.internal:3312"]
runcmd:
  - apt-get install pkg-config cmake clang lldb lld -y
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - apt-get install -y docker-compose
  - wget https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-amd64.tar.gz
  - tar -xvf prometheus-2.47.2.linux-amd64.tar.gz
  - cd prometheus-2.47.2.linux-amd64/ && rm prometheus.yml && mv /etc/prometheus.yml . && ./prometheus --config.file=prometheus.yml